#include<stdio.h>
#include<conio.h>

void bubble sort(int arr[]int n);
{
int,i,j,temp;
for(i=0,i<n;i++)
{
for(j=0;j<n -i-1;j++)
{
if(arr[j]>arr[i+1]
{
temp=arr[j+i];
arr[j+i]=temp;
}
}
}
printf("so the array is");
(i=0;i<n;i++)
{
printf("%d",arr[i]);
}
}
int main()
{
int arr[100],i,n
clrscr();
printf("\n enter the number of elements");
scanf("%d",i+1);
scanf("%d",&arr[i]);
}
bubble sort(arr,n);
getch();
return 0;
}
